#!/bin/env bash

REPODIR="$HOME/repos/arch"

copyrepo() {
	# Download the fresh repo to the desired directory and
	# later copy the files over to ~.
	echo "Updating dotfiles repo from github..."
	cd "$REPODIR" || exit
	git pull || exit
	echo "Copying dotfiles over to your home directory..."
	cp -rfT "$REPODIR" "$1"
	rm -rf "$HOME/.git" "$HOME/README.md" "$HOME/screenshot.png"

	# Update nvim plugins
	nvim -E -c "PlugInstall|visual|q|q" >/dev/null 2>&1
	nvim -E -c "PlugUpdate|visual|q|q" >/dev/null 2>&1

	# Refresh Xresources, shortcuts, wallpaper
	# and finally restart i3.
	xrdb ~/.Xresources >/dev/null 2>&1
	shortcuts >/dev/null 2>&1
	setbg >/dev/null 2>&1
	i3 restart >/dev/null 2>&1
	creload >/dev/null 2>&1
}

copyrepo "$HOME"
