#!/bin/env bash

REPODIR="$HOME/Repos/arch"

copyrepo() {
	echo "Updating dotfiles repo from github..."
	cd $REPODIR && git pull
	echo "Copying dotfiles over to your home directory..."
	cp -rfT "$REPODIR" "$1"
	rm -rf "$HOME/.git" "$HOME/README.md"
}

copyrepo "$HOME"
