#!/bin/env bash

putgitrepo() { # Downlods a gitrepo $1 and places the files in $2 only overwriting conflicts
	echo "Downloading and installing config files..."
	dir=$(mktemp -d)
	[ ! -d "$2" ] && mkdir -p "$2" && chown -R "$name:wheel" "$2"
	chown -R "$name:wheel" "$dir"
	git clone --depth 1 "$1" "$dir/gitrepo"
	cp -rfT "$dir/gitrepo" "$2"
}

putgitrepo "https://github.com/krook1024/arch.git" "$HOME"
rm -rf "$HOME/.git"
