#!/usr/bin/env bash

delete_current_config() { # Deletes the current configuration
	echo -n "Remove old font configuration (y/n)? "
	read answer
	if [ "$answer" != "${answer#[Yy]}" ] ;then
		sudo rm -rf /etc/fonts/conf.d/*
	fi
}

install_font_pkg() { # Installs needed packages
	yay -S --noconfirm --needed noto-fonts noto-fonts-emoji \
		noto-fonts-cjk ttf-symbola ttf-roboto ttf-dejavu \
		>/dev/null 2>&1

	# Hack
	echo "Installing Hack Nerd Font..."
	install_font_from_git "Hack Regular.ttf" \
		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf"
	install_font_from_git "Hack Bold.ttf" \
		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete.ttf"
	install_font_from_git "Hack Italic.ttf" \
		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete.ttf"
	install_font_from_git "Hack BoldItalic.ttf" \
		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete.ttf"

	# Fura Code
	echo "Installing Fura Code Nerd Font..."
	install_font_from_git "FuraCode Regular.ttf" \
		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Regular/complete/Fura%20Code%20Regular%20Nerd%20Font%20Complete.ttf"
	install_font_from_git "FuraCoda Bold.ttf" \
		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Bold/complete/Fura%20Code%20Bold%20Nerd%20Font%20Complete.ttf"

	# Sauce Code Pro
	echo "Installing Sauce Code Pro Nerd Font"
	install_font_from_git "Sauce Code Pro Regular.ttf" \
		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/SourceCodePro/Regular/complete/Sauce%20Code%20Pro%20Nerd%20Font%20Complete.ttf"
	install_font_from_git "Sauce Code Pro Bold.ttf" \
		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/SourceCodePro/Bold/complete/Sauce%20Code%20Pro%20Bold%20Nerd%20Font%20Complete.ttf"
	install_font_from_git "Sauce Code Pro BoldItalic.ttf" \
		"https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/SourceCodePro/Bold-Italic/complete/Sauce%20Code%20Pro%20Bold%20Italic%20Nerd%20Font%20Complete.ttf"
}

install_font_from_git() {
	# Usage: install_font_from_git font_name font_url
	# We first download in a temporary directory so in
	# case the download fails, we don't end up littering /usr/share/..
	dir=$(mktemp -d)
	(:;:)		# Micro sleep
	cd $dir || return 1
	sudo curl -fLo "$1" "$2" >/dev/null 2>&1
	sudo cp -f $dir/* /usr/share/fonts/TTF
	(:;:)
	sudo rm -rf $dir
}

install_new_config() { # Symlinks configuration files to /etc/fonts/conf.d
	needed_cfg=(10-hinting-slight.conf \
		10-scale-bitmap-fonts.conf 10-sub-pixel-rgb.conf \
		11-lcdfilter-default.conf \
		30-metric-aliases.conf \
		50-user.conf 60-generic.conf \
		66-noto-sans.conf 66-noto-serif.conf \
		90-synthetic.conf)

	for i in "${needed_cfg[@]}"; do
		sudo ln -s "/etc/fonts/conf.avail/$i" "/etc/fonts/conf.d/"
	done
}

main() {
	delete_current_config || echo "Didn't delete \
		current font configuration!"

	echo "Installing font packages..."
	install_font_pkg || echo "Failed to install \
		font packages!"

	echo "Installing new font configuration..."
	install_new_config || echo "Failed to install \
		new font configuration!"

	echo "Refresing font cache..."
		sudo fc-cache -fv >/dev/null 2>&1 || "Failed to refresh \
			font cache!"
}

main || echo "Failed." && exit 1
