#!/usr/bin/env bash

delete_current_config() { # Deletes the current configuration
	echo -n "Remove old font configuration (y/n)? "
	read answer
	if [ "$answer" != "${answer#[Yy]}" ] ;then
		sudo rm -rf /etc/fonts/conf.d/*
	fi
}

install_font_pkg() { # Installs needed packages
	yay -S --noconfirm --needed noto-fonts noto-fonts-emoji \
		noto-fonts-cjk ttf-symbola ttf-roboto ttf-dejavu \
		>/dev/null 2>&1

	getNerdFont "Hack"
	getNerdFont "FiraCode"
	getNerdFont "SourceCodePro"
	getNerdFont "Ubuntu"
	getNerdFont "UbuntuMono"
}

getNerdFont() { # Downloads and installs a nerd font given a name
	name=$1
	echo "> Getting $1 (nerd font)..."
	dir=$(mktemp -d) && cd $dir
	echo "> Temporary directory created: $dir"
	echo "> Downloading archive..."
	local url="https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0"
	curl -fLo "tmp.zip" "$url/$name.zip" -# && unset url
	[[ ! -f tmp.zip ]] && {
		echo "Failed to download your file!"
		exit
	}
	echo "> Extracting archive..."
	unzip -d . "tmp.zip" >/dev/null 2>&1
	rm -f *Compatible.ttf
	rm -f *Mono.ttf
	rm -f *.zip
	echo "> Installing fonts:"
	ls *.ttf
	sudo mv -f *.ttf /usr/share/fonts/TTF/
	(:;:)
	echo "> Done! Cleaning up now..."
	rm -rf $dir
	unset dir
}

install_new_config() { # Symlinks configuration files to /etc/fonts/conf.d
	needed_cfg=(10-hinting-slight.conf \
		10-scale-bitmap-fonts.conf 10-sub-pixel-rgb.conf \
		11-lcdfilter-default.conf \
		30-metric-aliases.conf \
		50-user.conf 60-generic.conf \
		66-noto-sans.conf 66-noto-serif.conf \
		90-synthetic.conf)

	for i in "${needed_cfg[@]}"; do
		sudo ln -s "/etc/fonts/conf.avail/$i" "/etc/fonts/conf.d/"
	done
}

main() {
	delete_current_config || echo "Didn't delete \
		current font configuration!"

	echo "Installing font packages..."
	install_font_pkg || echo "Failed to install \
		font packages!"

	echo "Installing new font configuration..."
	install_new_config || echo "Failed to install \
		new font configuration!"

	echo "Refresing font cache..."
		sudo fc-cache -fv >/dev/null 2>&1 || "Failed to refresh \
			font cache!"
}

main || echo "Failed." && exit 1
