#!/bin/env bash

REPODIR="$HOME/repos/arch"

copyfiles() {
	cd ~ || return

	files=(\
	# Bash related
	.bashrc .bash_profile .profile .inputrc \
    # Zsh related \
    .zshrc .zprofile \
	# Tmux
	.tmux.conf \
	# Vim related
	.vimrc .config/nvim/init.vim .config/nvim/autoload/plug.vim \
	# X related
	.Xresources \
	# Font config \
	.config/fontconfig/fonts.conf \
	# Shortcut files
	.config/bmdirs .config/bmfiles .config/aliasrc \
	# Compton config
	.config/picom.conf  \
	# Wallpaper
	.config/wall.png  \
	# Git configuration
	.gitconfig \
	# Ranger configuration
	.config/ranger/rc.conf .config/ranger/rifle.conf \
	.config/ranger/shortcuts.conf \
	# Mpv
	.config/mpv/mpv.conf .config/mpv/input.conf \
	# Unix ascii art
	.scripts/unix)

	for file in "${files[@]}"; do
		cp -P --parents "$file" "$REPODIR"
	done
}

copydirs() {
	cd ~ || return

	directories=(.scripts/i3cmds .scripts/tools .scripts/university \
	.config/dunst \
	.config/i3 \
	.config/i3blocks \
	.config/i3status \
	.config/zathura \
	.config/nvim/UltiSnips \
	.config/nvim/indent \
    .config/nvim/ftplugin \
	.vim \
	.config/gtk-2.0 \
	.config/gtk-3.0 \
	.config/sxiv \
    .config/kitty \
    .config/rofi)
	for dir in "${directories[@]}"; do
		cp -P -r --parents "$dir" "$REPODIR"
	done
}

gitupdate() {
	cd "$REPODIR" && \
	git add . && \
    git commit -m "⬆ Update dotfiles (📅 $(date "+%F %H:%M:%S")) 👉" && \
	git push
}

updaterepo() {
	copyfiles || echo "Failed to copy files."
	copydirs || echo "Failed to copy directories."
	gitupdate || echo "Failed to upload changes to git."
}

updaterepo || echo "Faliora."
