#!/bin/env bash

REPODIR="$HOME/Repos/arch"

copyfiles() {
	cd ~
	files=(.bashrc .gitconfig .profile .vimrc \
	.xinitrc \
	.Xresources .gitconfig .bash_profile \
	.config/bmdirs .config/bmfiles \
	.config/compton.conf .config/aliasrc \
	.config/wall.png .inputrc .tmux.conf \
	.config/nvim/init.vim .config/nvim/autoload/plug.vim \
	.config/mimeapps.list )

	for file in "${files[@]}"; do
		cp -P --parents $file $REPODIR
	done
}

copydirs() {
#	cp -rf ~/.scripts $REPODIR

	cd ~
	directories=(.scripts \
	.config/dunst \
	.config/i3 \
	.config/i3blocks \
	.config/zathura \
	.config/ranger \
	.vim \
	.config/gtk-2.0
	.config/gtk-3.0)

	for dir in "${directories[@]}"; do
		cp -r --parents $dir $REPODIR
	done
}

gitupdate() {
	cd $REPODIR
	git add .
	git commit -m "Update to dotfiles on $(date)"
	git push
}

updaterepo() {
	copyfiles || echo "Failed to copy files."
	copydirs || echo "Failed to copy directories."
	gitupdate || echo "Failed to upload changes to git."
}

updaterepo || echo "Faliora."
