#!/bin/env bash

REPODIR="$HOME/Repos/arch"

copyfiles() {
	cd ~

	files=(\
	# Bash related
	.bashrc .bash_profile .zprofile .profile .inputrc \
	# Tmux
	.tmux.conf \
	# Vim related
	.vimrc .config/nvim/init.vim .config/nvim/autoload/plug.vim \
	# X related
	.xinitrc .Xresources \
	# Font config \
	.config/fontconfig/fonts.conf \
	# Shortcut files
	.config/bmdirs .config/bmfiles .config/aliasrc \
	# Compton config
	.config/compton.conf  \
	# Wallpaper
	.config/wall.png  \
	# Git configuration
	.gitconfig \
	# Default applications
	.config/mimeapps.list \
	# Ranger configuration
	.config/ranger/rc.conf .config/ranger/rifle.conf \
	.config/ranger/shortcuts.conf \
	# Unix ascii art
	.scripts/unix \
	# Chromium start flags
	.config/chromium-flags.conf)

	for file in "${files[@]}"; do
		cp -P --parents $file $REPODIR
	done
}

copydirs() {
	cd ~

	directories=(.scripts/i3cmds .scripts/statusbar .scripts/tools \
	.config/dunst \
	.config/i3 \
	.config/i3blocks \
	.config/zathura \
	.vim \
	.config/gtk-2.0
	.config/gtk-3.0)

	for dir in "${directories[@]}"; do
		cp -P -r --parents $dir $REPODIR
	done
}

gitupdate() {
	cd $REPODIR && \
	git add . && \
	git commit -m "Update to dotfiles on $(date)" && \
	git push
}

updaterepo() {
	copyfiles || echo "Failed to copy files."
	copydirs || echo "Failed to copy directories."
	gitupdate || echo "Failed to upload changes to git."
}

updaterepo || echo "Faliora."
