#!/bin/sh
alias ka="killall" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c Magit" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="vifm" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="lsd --group-dirs=\"first\"" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best --audio-format mp3" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
	r="ranger" \
	ind="indent -l70 -linux" \
	update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
	pkgfiles="pacman -Qlq" \
	rp="source ~/.profile" \
	checkf="aspell -l hu -H -c" \
	updatemirrors='sudo reflector --verbose --country France --country Germany --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist; sudo rm -f /etc/pacman.d/mirrorlist.pacnew' \
	n="setsid samedir" \
	bt="bluetoothctl" \
	nf='neofetch --disable gpu resolution icons theme  --ascii "$(fortune | cowsay -W 30 | lolcat)" | lolcat'

command -v nvim >/dev/null &&
	alias vim="nvim" vimdiff="nvim -d"

shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ;}
se() { du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf | xargs  -r $EDITOR ;}
sup() { du -a ~/Repos/udprog-code/source/* | awk '{print $2}' | fzf | xargs -r $EDITOR ;}
sv() { vcopy "$(du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf)" ;}
vf() { fzf | xargs -r -I % $EDITOR % ;}
quickgit() { git add . ; git commit -m "$*" ; git push ;}
printunicode() { printf "\u$1\n" ; }
