#!/bin/sh
alias ka="killall" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c Magit" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="vifm" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
	r="ranger" \
	nf="neofetch | lolcat" \
	ind="indent -l70 -linux" \
	update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
	pkgfiles="pacman -Qlq" \
	rp="source ~/.profile" \
	checkf="aspell -l hu -H -c" \
	updatemirrors="p -S --noconfirm pacman-mirrorlist" \
	n="setsid samedir"

command -v nvim >/dev/null &&
	alias vim="nvim" vimdiff="nvim -d"

shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ;}
se() { du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf | xargs  -r $EDITOR ;}
sv() { vcopy "$(du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf)" ;}
vf() { fzf | xargs -r -I % $EDITOR % ;}
quickgit() { git add . ; git commit -m "$*" ; git push ;}
