#!/usr/bin/env sh

# Set to "no" to disable colors (everything will be in white instead)
colors="yes"
[[ $colors == "no" ]] && { printf "<span color=\"#FFFFFF\">"; exit 0; }
unset colors

color=$(xrdb -query | grep "*color$1:" | awk '{print $NF}')
[[ $color == "" ]] && printf "<span color=\"#FFFFFF\">" || printf "<span color=\"$color\">"
