#!/usr/bin/env sh
# This script is responsible for coloring i3blocks' output.
# By default it returns colors from xrdb accordingly to the output.
# Usage: blockcolor [number]

# Set to "no" to disable colors (everything will be in white instead)
colors="yes"
[[ $colors == "no" ]] && { printf "<span color=\"#FFFFFF\">"; exit 0; }
unset colors

color=$(xrdb -query | grep "*color$1:" | awk '{print $NF}')
[[ $color == "" ]] && printf "<span color=\"#FFFFFF\">" || printf "<span color=\"$color\">"
