#!/bin/sh
case "$(printf "a selected area\\na selected area with shadow\\ncurrent window\\ncurrent window with shadow\\nfull screen\\na selected area (copy)\\ncurrent window (copy)\\nfull screen (copy)" | dmenu -l 6 -i -p "Screenshot which area?")" in
	"a selected area") maim -s pic-selected-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"a selected area with shadow") maim -s | convert - \( +clone -background black -shadow 80x10+0+0 \) +swap -background none -layers merge +repage pic-selected-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"current window") maim -i "$(xdotool getactivewindow)" pic-window-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"current window with shadow") maim -i "$(xdotool getactivewindow)" | convert - \( +clone -background black -shadow 80x10+0+0 \) +swap -background none -layers merge +repage pic-window-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"full screen") maim pic-full-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"a selected area (copy)") maim -s | xclip -selection clipboard -t image/png ;;
	"current window (copy)") maim -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
	"full screen (copy)") maim | xclip -selection clipboard -t image/png ;;
esac








# ~ ➜ maim -st 9999999 | convert - \( +clone -background black -shadow 80x10+0+0 \) +swap -background none -layers merge +repage shadow.png
